//! Contains tag types and utility functions.

/// Duplicate of [`TagType`](lofty::tag::TagType) from [lofty](https://crates.io/crates/lofty), except with [`Serialize`](serde::Serialize) and [`Deserialize`](serde::Deserialize) traits implemented.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TagType {
    Ape,
    Id3v1,
    Id3v2,
    Mp4Ilst,
    VorbisComments,
    RiffInfo,
    AiffText,
}

/// The Item Keys that a [`Tag`](lofty::tag::Tag) can have, essentially is the same as Lofty's [`ItemKey`](lofty::tag::ItemKey) but copies some names from [MusicBrainz Picard Tag Mapping](https://picard-docs.musicbrainz.org/downloads/MusicBrainz_Picard_Tag_Map.html) spec.
///
/// Additionally, this enum has the [`Serialize`](serde::Serialize) and [`Deserialize`](serde::Deserialize) traits implemented and maps to and from Lofty [`ItemKey`](lofty::tag::ItemKey).
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ItemKey {
    Album,
    AlbumArtist,
    AlbumSort,
    Artist,
    ArtistSort,
    Artists,
    Barcode,
    Bpm,
    CatalogNumber,
    Comment,
    Composer,
    ComposerSortOrder,
    Conductor,
    Copyright,
    Director,
    DiscNumber,
    DiscTotal,
    EncodedBy,
    EncoderSettings,
    Engineer,
    Genre,
    Grouping,
    Key,
    Isrc,
    Language,
    License,
    Lyricist,
    Lyrics,
    Mood,
    Movement,
    MovementNumber,
    MovementTotal,
    MusicBrainzRecordingId,
    MusicBrainzTrackId,
    MusicBrainzReleaseId,
    MusicBrainzReleaseGroupId,
    MusicBrainzArtistId,
    MusicBrainzReleaseArtistId,
    MusicBrainzWorkId,
    OriginalAlbum,
    OriginalArtist,
    OriginalFileName,
    OriginalReleaseDate,
    Performer,
    Producer,
    Label,
    ReleaseDate,
    RecordingDate,
    Title,
    TitleSort,
    TrackNumber,
    TrackTotal,
    Website,
    Work,
    Writer,
    Year,
    SetSubtitle,
    ShowName,
    TrackSubtitle,
    OriginalLyricist,
    AlbumTitleSortOrder,
    ShowNameSortOrder,
    Arranger,
    MixDj,
    MixEngineer,
    MusicianCredits,
    Publisher,
    InternetRadioStationName,
    InternetRadioStationOwner,
    Remixer,
    Popularimeter,
    ParentalAdvisory,
    FlagCompilation,
    FlagPodcast,
    FileType,
    FileOwner,
    TaggingTime,
    Length,
    OriginalMediaType,
    EncoderSoftware,
    EncodingTime,
    ReplayGainAlbumGain,
    ReplayGainAlbumPeak,
    ReplayGainTrackGain,
    ReplayGainTrackPeak,
    AudioFileUrl,
    AudioSourceUrl,
    CommercialInformationUrl,
    CopyrightUrl,
    RadioStationUrl,
    PaymentUrl,
    PublisherUrl,
    IntegerBpm,
    Color,
    PodcastDescription,
    PodcastSeriesCategory,
    PodcastUrl,
    PodcastGlobalUniqueId,
    PodcastKeywords,
    Description,
    Script,
    AppleXid,
    AppleId3v2ContentGroup,

    Unknown,
}

impl From<ItemKey> for lofty::tag::ItemKey {
    fn from(value: ItemKey) -> Self {
        match value {
            ItemKey::Album => Self::AlbumTitle,
            ItemKey::AlbumArtist => Self::AlbumArtist,
            ItemKey::AlbumSort => Self::AlbumArtistSortOrder,
            ItemKey::Artist => Self::TrackArtist,
            ItemKey::ArtistSort => Self::TrackArtistSortOrder,
            ItemKey::Artists => Self::TrackArtists,
            ItemKey::Barcode => Self::Barcode,
            ItemKey::Bpm => Self::Bpm,
            ItemKey::CatalogNumber => Self::CatalogNumber,
            ItemKey::Comment => Self::Comment,
            ItemKey::Composer => Self::Composer,
            ItemKey::ComposerSortOrder => Self::ComposerSortOrder,
            ItemKey::Conductor => Self::Conductor,
            ItemKey::Copyright => Self::CopyrightMessage,
            ItemKey::Director => Self::Director,
            ItemKey::DiscNumber => Self::DiscNumber,
            ItemKey::DiscTotal => Self::DiscTotal,
            ItemKey::EncodedBy => Self::EncodedBy,
            ItemKey::EncoderSettings => Self::EncoderSettings,
            ItemKey::Engineer => Self::Engineer,
            ItemKey::Genre => Self::Genre,
            ItemKey::Grouping => Self::ContentGroup,
            ItemKey::Key => Self::InitialKey,
            ItemKey::Isrc => Self::Isrc,
            ItemKey::Language => Self::Language,
            ItemKey::License => Self::License,
            ItemKey::Lyricist => Self::Lyricist,
            ItemKey::Lyrics => Self::Lyrics,
            ItemKey::Mood => Self::Mood,
            ItemKey::Movement => Self::Movement,
            ItemKey::MovementNumber => Self::MovementNumber,
            ItemKey::MovementTotal => Self::MovementTotal,
            ItemKey::MusicBrainzRecordingId => Self::MusicBrainzRecordingId,
            ItemKey::MusicBrainzTrackId => Self::MusicBrainzTrackId,
            ItemKey::MusicBrainzReleaseId => Self::MusicBrainzReleaseId,
            ItemKey::MusicBrainzReleaseGroupId => Self::MusicBrainzReleaseGroupId,
            ItemKey::MusicBrainzArtistId => Self::MusicBrainzArtistId,
            ItemKey::MusicBrainzReleaseArtistId => Self::MusicBrainzReleaseArtistId,
            ItemKey::MusicBrainzWorkId => Self::MusicBrainzWorkId,
            ItemKey::OriginalAlbum => Self::OriginalAlbumTitle,
            ItemKey::OriginalArtist => Self::OriginalArtist,
            ItemKey::OriginalFileName => Self::OriginalFileName,
            ItemKey::OriginalReleaseDate => Self::OriginalReleaseDate,
            ItemKey::Performer => Self::Performer,
            ItemKey::Producer => Self::Producer,
            ItemKey::Label => Self::Label,
            ItemKey::ReleaseDate => Self::ReleaseDate,
            ItemKey::RecordingDate => Self::RecordingDate,
            ItemKey::Title => Self::TrackTitle,
            ItemKey::TitleSort => Self::TrackTitleSortOrder,
            ItemKey::TrackNumber => Self::TrackNumber,
            ItemKey::TrackTotal => Self::TrackTotal,
            ItemKey::Website => Self::TrackArtistUrl,
            ItemKey::Work => Self::Work,
            ItemKey::Writer => Self::Writer,
            ItemKey::Year => Self::Year,
            ItemKey::SetSubtitle => Self::SetSubtitle,
            ItemKey::ShowName => Self::ShowName,
            ItemKey::TrackSubtitle => Self::TrackSubtitle,
            ItemKey::OriginalLyricist => Self::OriginalLyricist,
            ItemKey::AlbumTitleSortOrder => Self::AlbumTitleSortOrder,
            ItemKey::ShowNameSortOrder => Self::ShowNameSortOrder,
            ItemKey::Arranger => Self::Arranger,
            ItemKey::MixDj => Self::MixDj,
            ItemKey::MixEngineer => Self::MixEngineer,
            ItemKey::MusicianCredits => Self::MusicianCredits,
            ItemKey::Publisher => Self::Publisher,
            ItemKey::InternetRadioStationName => Self::InternetRadioStationName,
            ItemKey::InternetRadioStationOwner => Self::InternetRadioStationOwner,
            ItemKey::Remixer => Self::Remixer,
            ItemKey::Popularimeter => Self::Popularimeter,
            ItemKey::ParentalAdvisory => Self::ParentalAdvisory,
            ItemKey::FlagCompilation => Self::FlagCompilation,
            ItemKey::FlagPodcast => Self::FlagPodcast,
            ItemKey::FileType => Self::FileType,
            ItemKey::FileOwner => Self::FileOwner,
            ItemKey::TaggingTime => Self::TaggingTime,
            ItemKey::Length => Self::Length,
            ItemKey::OriginalMediaType => Self::OriginalMediaType,
            ItemKey::EncoderSoftware => Self::EncoderSoftware,
            ItemKey::EncodingTime => Self::EncodingTime,
            ItemKey::ReplayGainAlbumGain => Self::ReplayGainAlbumGain,
            ItemKey::ReplayGainAlbumPeak => Self::ReplayGainAlbumPeak,
            ItemKey::ReplayGainTrackGain => Self::ReplayGainTrackGain,
            ItemKey::ReplayGainTrackPeak => Self::ReplayGainTrackPeak,
            ItemKey::AudioFileUrl => Self::AudioFileUrl,
            ItemKey::AudioSourceUrl => Self::AudioSourceUrl,
            ItemKey::CommercialInformationUrl => Self::CommercialInformationUrl,
            ItemKey::CopyrightUrl => Self::CopyrightUrl,
            ItemKey::RadioStationUrl => Self::RadioStationUrl,
            ItemKey::PaymentUrl => Self::PaymentUrl,
            ItemKey::PublisherUrl => Self::PublisherUrl,
            ItemKey::IntegerBpm => Self::IntegerBpm,
            ItemKey::Color => Self::Color,
            ItemKey::PodcastDescription => Self::PodcastDescription,
            ItemKey::PodcastSeriesCategory => Self::PodcastSeriesCategory,
            ItemKey::PodcastUrl => Self::PodcastUrl,
            ItemKey::PodcastGlobalUniqueId => Self::PodcastGlobalUniqueId,
            ItemKey::PodcastKeywords => Self::PodcastKeywords,
            ItemKey::Description => Self::Description,
            ItemKey::Script => Self::Script,
            ItemKey::AppleXid => Self::AppleXid,
            ItemKey::AppleId3v2ContentGroup => Self::AppleId3v2ContentGroup,

            ItemKey::Unknown => Self::Unknown(String::new()),
        }
    }
}

impl From<lofty::tag::ItemKey> for ItemKey {
    fn from(value: lofty::tag::ItemKey) -> Self {
        match value {
            lofty::tag::ItemKey::AlbumTitle => ItemKey::Album,
            lofty::tag::ItemKey::AlbumArtist => ItemKey::AlbumArtist,
            lofty::tag::ItemKey::AlbumArtistSortOrder => ItemKey::AlbumSort,
            lofty::tag::ItemKey::TrackArtist => ItemKey::Artist,
            lofty::tag::ItemKey::TrackArtistSortOrder => ItemKey::ArtistSort,
            lofty::tag::ItemKey::TrackArtists => ItemKey::Artists,
            lofty::tag::ItemKey::Bpm => ItemKey::Bpm,
            lofty::tag::ItemKey::Barcode => ItemKey::Barcode,
            lofty::tag::ItemKey::CatalogNumber => ItemKey::CatalogNumber,
            lofty::tag::ItemKey::Comment => ItemKey::Comment,
            lofty::tag::ItemKey::Composer => ItemKey::Composer,
            lofty::tag::ItemKey::ComposerSortOrder => ItemKey::ComposerSortOrder,
            lofty::tag::ItemKey::Conductor => ItemKey::Conductor,
            lofty::tag::ItemKey::CopyrightMessage => ItemKey::Copyright,
            lofty::tag::ItemKey::Director => ItemKey::Director,
            lofty::tag::ItemKey::DiscNumber => ItemKey::DiscNumber,
            lofty::tag::ItemKey::DiscTotal => ItemKey::DiscTotal,
            lofty::tag::ItemKey::EncodedBy => ItemKey::EncodedBy,
            lofty::tag::ItemKey::EncoderSettings => ItemKey::EncoderSettings,
            lofty::tag::ItemKey::Engineer => ItemKey::Engineer,
            lofty::tag::ItemKey::Genre => ItemKey::Genre,
            lofty::tag::ItemKey::ContentGroup => ItemKey::Grouping,
            lofty::tag::ItemKey::InitialKey => ItemKey::Key,
            lofty::tag::ItemKey::Isrc => ItemKey::Isrc,
            lofty::tag::ItemKey::Language => ItemKey::Language,
            lofty::tag::ItemKey::Lyricist => ItemKey::Lyricist,
            lofty::tag::ItemKey::Lyrics => ItemKey::Lyrics,
            lofty::tag::ItemKey::Mood => ItemKey::Mood,
            lofty::tag::ItemKey::Movement => ItemKey::Movement,
            lofty::tag::ItemKey::MovementNumber => ItemKey::MovementNumber,
            lofty::tag::ItemKey::MovementTotal => ItemKey::MovementTotal,
            lofty::tag::ItemKey::MusicBrainzRecordingId => ItemKey::MusicBrainzRecordingId,
            lofty::tag::ItemKey::MusicBrainzTrackId => ItemKey::MusicBrainzTrackId,
            lofty::tag::ItemKey::MusicBrainzReleaseId => ItemKey::MusicBrainzReleaseId,
            lofty::tag::ItemKey::MusicBrainzReleaseGroupId => ItemKey::MusicBrainzReleaseGroupId,
            lofty::tag::ItemKey::MusicBrainzArtistId => ItemKey::MusicBrainzArtistId,
            lofty::tag::ItemKey::MusicBrainzReleaseArtistId => ItemKey::MusicBrainzReleaseArtistId,
            lofty::tag::ItemKey::MusicBrainzWorkId => ItemKey::MusicBrainzWorkId,
            lofty::tag::ItemKey::OriginalAlbumTitle => ItemKey::OriginalAlbum,
            lofty::tag::ItemKey::OriginalArtist => ItemKey::OriginalArtist,
            lofty::tag::ItemKey::OriginalFileName => ItemKey::OriginalFileName,
            lofty::tag::ItemKey::OriginalReleaseDate => ItemKey::OriginalReleaseDate,
            lofty::tag::ItemKey::Performer => ItemKey::Performer,
            lofty::tag::ItemKey::Producer => ItemKey::Producer,
            lofty::tag::ItemKey::Label => ItemKey::Label,
            lofty::tag::ItemKey::ReleaseDate => ItemKey::ReleaseDate,
            lofty::tag::ItemKey::RecordingDate => ItemKey::RecordingDate,
            lofty::tag::ItemKey::TrackTitle => ItemKey::Title,
            lofty::tag::ItemKey::TrackTitleSortOrder => ItemKey::TitleSort,
            lofty::tag::ItemKey::TrackNumber => ItemKey::TrackNumber,
            lofty::tag::ItemKey::TrackTotal => ItemKey::TrackTotal,
            lofty::tag::ItemKey::TrackArtistUrl => ItemKey::Website,
            lofty::tag::ItemKey::Work => ItemKey::Work,
            lofty::tag::ItemKey::Writer => ItemKey::Writer,
            lofty::tag::ItemKey::Year => ItemKey::Year,
            lofty::tag::ItemKey::SetSubtitle => ItemKey::SetSubtitle,
            lofty::tag::ItemKey::ShowName => ItemKey::ShowName,
            lofty::tag::ItemKey::TrackSubtitle => ItemKey::TrackSubtitle,
            lofty::tag::ItemKey::OriginalLyricist => ItemKey::OriginalLyricist,
            lofty::tag::ItemKey::AlbumTitleSortOrder => ItemKey::AlbumTitleSortOrder,
            lofty::tag::ItemKey::ShowNameSortOrder => ItemKey::ShowNameSortOrder,
            lofty::tag::ItemKey::Arranger => ItemKey::Arranger,
            lofty::tag::ItemKey::MixDj => ItemKey::MixDj,
            lofty::tag::ItemKey::MixEngineer => ItemKey::MixEngineer,
            lofty::tag::ItemKey::MusicianCredits => ItemKey::MusicianCredits,
            lofty::tag::ItemKey::Publisher => ItemKey::Publisher,
            lofty::tag::ItemKey::InternetRadioStationName => ItemKey::InternetRadioStationName,
            lofty::tag::ItemKey::InternetRadioStationOwner => ItemKey::InternetRadioStationOwner,
            lofty::tag::ItemKey::Remixer => ItemKey::Remixer,
            lofty::tag::ItemKey::Popularimeter => ItemKey::Popularimeter,
            lofty::tag::ItemKey::ParentalAdvisory => ItemKey::ParentalAdvisory,
            lofty::tag::ItemKey::FlagCompilation => ItemKey::FlagCompilation,
            lofty::tag::ItemKey::FlagPodcast => ItemKey::FlagPodcast,
            lofty::tag::ItemKey::FileType => ItemKey::FileType,
            lofty::tag::ItemKey::FileOwner => ItemKey::FileOwner,
            lofty::tag::ItemKey::TaggingTime => ItemKey::TaggingTime,
            lofty::tag::ItemKey::Length => ItemKey::Length,
            lofty::tag::ItemKey::OriginalMediaType => ItemKey::OriginalMediaType,
            lofty::tag::ItemKey::EncoderSoftware => ItemKey::EncoderSoftware,
            lofty::tag::ItemKey::EncodingTime => ItemKey::EncodingTime,
            lofty::tag::ItemKey::ReplayGainAlbumGain => ItemKey::ReplayGainAlbumGain,
            lofty::tag::ItemKey::ReplayGainAlbumPeak => ItemKey::ReplayGainAlbumPeak,
            lofty::tag::ItemKey::ReplayGainTrackGain => ItemKey::ReplayGainTrackGain,
            lofty::tag::ItemKey::ReplayGainTrackPeak => ItemKey::ReplayGainTrackPeak,
            lofty::tag::ItemKey::AudioFileUrl => ItemKey::AudioFileUrl,
            lofty::tag::ItemKey::AudioSourceUrl => ItemKey::AudioSourceUrl,
            lofty::tag::ItemKey::CommercialInformationUrl => ItemKey::CommercialInformationUrl,
            lofty::tag::ItemKey::CopyrightUrl => ItemKey::CopyrightUrl,
            lofty::tag::ItemKey::RadioStationUrl => ItemKey::RadioStationUrl,
            lofty::tag::ItemKey::PaymentUrl => ItemKey::PaymentUrl,
            lofty::tag::ItemKey::PublisherUrl => ItemKey::PublisherUrl,
            lofty::tag::ItemKey::IntegerBpm => ItemKey::IntegerBpm,
            lofty::tag::ItemKey::Color => ItemKey::Color,
            lofty::tag::ItemKey::PodcastDescription => ItemKey::PodcastDescription,
            lofty::tag::ItemKey::PodcastSeriesCategory => ItemKey::PodcastSeriesCategory,
            lofty::tag::ItemKey::PodcastUrl => ItemKey::PodcastUrl,
            lofty::tag::ItemKey::PodcastGlobalUniqueId => ItemKey::PodcastGlobalUniqueId,
            lofty::tag::ItemKey::PodcastKeywords => ItemKey::PodcastKeywords,
            lofty::tag::ItemKey::Description => ItemKey::Description,
            lofty::tag::ItemKey::Script => ItemKey::Script,
            lofty::tag::ItemKey::AppleXid => ItemKey::AppleXid,
            lofty::tag::ItemKey::AppleId3v2ContentGroup => ItemKey::AppleId3v2ContentGroup,

            _ => ItemKey::Unknown,
        }
    }
}

impl From<TagType> for lofty::tag::TagType {
    fn from(value: TagType) -> Self {
        match value {
            TagType::Ape => lofty::tag::TagType::Ape,
            TagType::Id3v1 => lofty::tag::TagType::Id3v1,
            TagType::Id3v2 => lofty::tag::TagType::Id3v2,
            TagType::Mp4Ilst => lofty::tag::TagType::Mp4Ilst,
            TagType::VorbisComments => lofty::tag::TagType::VorbisComments,
            TagType::RiffInfo => lofty::tag::TagType::RiffInfo,
            TagType::AiffText => lofty::tag::TagType::AiffText,
        }
    }
}

impl From<lofty::tag::TagType> for TagType {
    fn from(value: lofty::tag::TagType) -> Self {
        match value {
            lofty::tag::TagType::Ape => TagType::Ape,
            lofty::tag::TagType::Id3v1 => TagType::Id3v1,
            lofty::tag::TagType::Id3v2 => TagType::Id3v2,
            lofty::tag::TagType::Mp4Ilst => TagType::Mp4Ilst,
            lofty::tag::TagType::VorbisComments => TagType::VorbisComments,
            lofty::tag::TagType::RiffInfo => TagType::RiffInfo,
            lofty::tag::TagType::AiffText => TagType::AiffText,

            // NOTE: Unsure why this is needed.
            _ => TagType::Id3v2,
        }
    }
}
