// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseSong } from "./DatabaseSong";

/**
 * A collection of songs. Does not correlate to a table in the database.
 */
export type Album = { title: string, artist: string | null, tracks: Array<DatabaseSong>, };
