// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongMetadata } from "./SongMetadata";

export type Album = { title: string, tracks: Array<SongMetadata>, barcode: string | null, catalogNumber: string | null, comment: string | null, country: string | null, artist: string | null, label: string | null, date: string | null, originalDate: string | null, };
