// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemInfo } from "./SystemInfo";

export type AppInfo = { 
/**
 * The version number of the application
 */
version: string, 
/**
 * The name of the application
 */
name: string, 
/**
 * System information that the application is running on
 */
system: SystemInfo, };
