// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileOperationEvent = { "type": "failed", source: bigint, error: string, } | { "type": "started", source: bigint, } | { "type": "completed", source: bigint, } | { "type": "cancelled", source: bigint, } | { "type": "progress", source: bigint, bytes: bigint, total_bytes: bigint, current_dir: number, dir_count: number, };

export type FileOperationState = { "kind": "move", to_from: { [key in string]?: Array<string> }, status: FileSystemOperationStatus, } | { "kind": "copy", to_from: { [key in string]?: Array<string> }, status: FileSystemOperationStatus, } | { "kind": "delete", paths: Array<string>, status: FileSystemOperationStatus, };

export type FileSystemOperationStatus = "pending" | "inProgress";
