// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Directory = { 
/**
 * The name of the directory.
 */
name: string, 
/**
 * The path of the directory.
 */
path: string, 
/**
 * The display name of the directory, only used in the UI.
 */
displayName: string | null, 
/**
 * The size of the directory takes up in bytes.
 */
pathSize: bigint | null, 
/**
 * The free space of the hard drive the directory is stored on.
 */
freeSpace: bigint | null, 
/**
 * The total space of the hard drive the directory is stored on.
 */
totalSpace: bigint | null, };
