// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Directory = { name: string, path: string, pathSize: bigint | null, freeSpace: bigint | null, totalSpace: bigint | null, };
