// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileOperationEvent = { source: string, timestamp: Date, } & ({ "kind": "started" } | { "kind": "completed" } | { "kind": "cancelled" } | { "kind": "progress", bytes: bigint, total_bytes: bigint, current_dir: number, dir_count: number, });
