// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Similar to [`FileType`] from [lofty](https://crates.io/crates/lofty), except with [`Serialize`] and [`Deserialize`] traits implemented.
 */
export type SongFileType = "aac" | "aiff" | "ape" | "flac" | "mpeg" | "mp4" | "mpc" | "opus" | "vorbis" | "speex" | "wav" | "wavPack" | "unknown";
