// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Duplicate of [`TagType`](lofty::tag::TagType) from [lofty](https://crates.io/crates/lofty), except with [`Serialize`](serde::Serialize) and [`Deserialize`](serde::Deserialize) traits implemented.
 */
export type TagType = "ape" | "id3v1" | "id3v2" | "mp4Ilst" | "vorbisComments" | "riffInfo" | "aiffText";
