// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskEventType } from "./TaskEventType";

export type TaskEvent = { kind: TaskEventType, message: string, current: bigint | null, total: bigint | null, step: number | null, timestamp: Date, };
