// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type TaskInfo = { id: string, name: string, description: string, steps: number, status: TaskStatus, completedAt: Date, startedAt: Date, stoppedAt: Date, };
