// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewDatabaseSong = { path: string, title: string | null, artist: string | null, album: string | null, albumArtist: string | null, genre: string | null, trackNumber: string | null, discNumber: string | null, year: string | null, mood: string | null, fileCreatedAt: Date, };
