// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewDirectory = { 
/**
 * The path of the directory.
 */
path: string, 
/**
 * The display name of the directory, only used in the UI.
 */
displayName: string | null, };
