// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongFileType } from "./SongFileType";
import type { SongMetadata } from "./SongMetadata";
import type { TagType } from "./TagType";

export type SongFile = { 
/**
 * The path to the file
 */
path: string, 
/**
 * The type of metadata format used
 */
tagType: TagType, 
/**
 * The type of file
 */
fileType: SongFileType, 
/**
 * System time when the file was created
 */
created: Date, 
/**
 * System time when the file was last modified
 */
lastModified: Date, 
/**
 * The size of the file
 */
size: bigint, 
/**
 * Metadata contained in the file
 */
metadata: SongMetadata | null, };
