// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemInfo = { 
/**
 * The name of the operating system, e.g. "Windows", "Ubuntu", "Darwin"
 */
os: string, 
/**
 * The name of the computer
 */
name: string, };
