// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskEventType = "initial" | "info" | "error" | "warning" | "progress" | "complete" | "start" | "stop";
