// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatedSong = { title: string | null, artist: string | null, album: string | null, album_artist: string | null, genre: string | null, track_number: string | null, disc_number: string | null, year: string | null, mood: string | null, };
